"""
Declarative base and shared column conventions.

This module deliberately imports NO models — the models import from it, so importing them
back here would create a cycle. Anything needing a fully populated `Base.metadata`
(Alembic, table creation in tests) must `import backend.app.models` explicitly.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all DropoutGuard tables."""


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key, generated by Postgres by default and by Python for ORM inserts."""
    return mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at maintained by the database clock, not the app clock."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
