import evidenceData from './evidence.json';

// Model results for the site, read only through here. evidence.json is generated by
// scripts/export_site_evidence.py and is large, so only lazily loaded chunks import this module.

export const evidenceProvenance = evidenceData.provenance;
// Confidence level (%) of every ci_lower/ci_upper, exported from the evaluation harness setting.
export const ciLevelPct = evidenceData.ci_level_pct;

// Exactly one result row must match; anything else throws in development (a typo or a stale export).
export const findResult = (criteria) => {
  const matches = evidenceData.results.filter((row) =>
    Object.entries(criteria).every(([key, value]) => row[key] === value)
  );
  if (matches.length !== 1 && import.meta.env.DEV) {
    throw new Error(`Expected one evidence row for ${JSON.stringify(criteria)}, found ${matches.length}.`);
  }
  return matches[0];
};

export const findResults = (criteria) =>
  evidenceData.results.filter((row) => Object.entries(criteria).every(([key, value]) => row[key] === value));

export const formatScore = (value) => value.toFixed(2);
