"""
Export Site Evidence Script
Reads benchmark JSON artifacts from ml/artifacts/benchmarks/ and writes
frontend/src/content/evidence.json, the only source of model results shown on the public site.

Values are copied exactly as stored in the artifacts: no rounding, no derived numbers. The output
carries no timestamp, so re-running on unchanged artifacts produces an identical file.

Usage:
    python -m scripts.export_site_evidence                  # UCI 697 only
    python -m scripts.export_site_evidence --include-oulad  # UCI 697 + OULAD earliness snapshots
"""

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any, Dict, List

from ml.provenance import ProvenanceError, assert_consistent_provenance, load_labelled_json

BASE_DIR = Path(__file__).resolve().parents[1]
BENCHMARK_DIR = BASE_DIR / "ml" / "artifacts" / "benchmarks"
EVIDENCE_PATH = BASE_DIR / "frontend" / "src" / "content" / "evidence.json"
REGENERATE_HINT = "python -m ml.pipeline run-all"

UCI_FILES = [
    "uci_enrolment_time_primary.json",
    "uci_end_of_sem1_primary.json",
    "uci_full_primary.json",
]
OULAD_FILES = [
    "oulad_snapshot_t14_withdrawn.json",
    "oulad_snapshot_t28_withdrawn.json",
    "oulad_snapshot_t56_withdrawn.json",
    "oulad_snapshot_t84_withdrawn.json",
]

README_TEXT = (
    "Generated by scripts/export_site_evidence.py from ml/artifacts/benchmarks/. Do not edit by hand; "
    "re-run the script after the benchmarks are regenerated."
)


def selected_files(include_oulad: bool) -> List[str]:
    return UCI_FILES + (OULAD_FILES if include_oulad else [])


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _rows(art: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = []
    for split, models in art["results"].items():
        for model, res in models.items():
            row: Dict[str, Any] = {
                "dataset": art["dataset"],
                "feature_set": art["feature_set"],
                "label_variant": art["label_variant"],
            }
            if "snapshot_t" in art:
                row["snapshot_t"] = art["snapshot_t"]
            row.update({
                "n_samples": art["n_samples"],
                "total_positives": art["total_positives"],
                "prevalence": art["prevalence"],
                "split": split,
                "model": model,
                "n_evaluated": res["n_evaluated"],
                "metrics_pooling": res["metrics_pooling"],
                "metrics": res["metrics"],
            })
            if "per_fold" in res:
                row["per_fold_summary"] = res["per_fold"]["summary"]
            rows.append(row)
    return rows


def build_evidence(benchmark_dir: Path = BENCHMARK_DIR, include_oulad: bool = False) -> Dict[str, Any]:
    names = selected_files(include_oulad)
    paths = [benchmark_dir / name for name in names]
    missing = [p.name for p in paths if not p.exists()]
    if missing:
        raise FileNotFoundError(
            f"Benchmark artifacts missing from {benchmark_dir}: {missing}. Regenerate them with `{REGENERATE_HINT}`."
        )

    artifacts = load_labelled_json(paths)
    assert_consistent_provenance(artifacts)
    dirty = sorted(name for name, art in artifacts.items() if art["provenance"].get("git_dirty"))
    if dirty:
        raise ProvenanceError(
            f"Refusing to export: these artifacts were generated from a working tree with uncommitted "
            f"changes (git_dirty=true): {dirty}. Regenerate them from a clean tree with `{REGENERATE_HINT}`."
        )

    run_ids = {art["provenance"].get("run_id") for art in artifacts.values()}
    if len(run_ids) != 1:
        raise ProvenanceError(f"Refusing to export: artifacts record different run ids {sorted(map(str, run_ids))}.")

    first = artifacts[names[0]]["provenance"]
    return {
        "_readme": README_TEXT,
        "options": {"include_oulad": include_oulad},
        "provenance": {
            "run_id": first["run_id"],
            "git_commit": first["git_commit"],
            "source_files": {p.name: {"sha256": _sha256(p)} for p in paths},
        },
        "results": [row for name in names for row in _rows(artifacts[name])],
    }


def render(evidence: Dict[str, Any]) -> str:
    return json.dumps(evidence, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export benchmark results for the public site.")
    parser.add_argument(
        "--include-oulad", action="store_true", help="Also export the OULAD earliness snapshots (t = 14, 28, 56, 84)."
    )
    args = parser.parse_args()

    evidence = build_evidence(include_oulad=args.include_oulad)
    EVIDENCE_PATH.write_text(render(evidence), encoding="utf-8")
    print(
        f"Wrote {len(evidence['results'])} result rows to {EVIDENCE_PATH.relative_to(BASE_DIR)} "
        f"(run {evidence['provenance']['run_id']}, include_oulad={args.include_oulad})."
    )


if __name__ == "__main__":
    main()
