"""
Renders verification/REPORT.md from a fresh run of the verification suite.

The report is built ONLY from:
- the junit XML written by `python -m pytest verification --junitxml=<tmp>`
  (test id, outcome, skip reason, failure message per test case, and the suite totals)
- `git rev-parse HEAD` and whether tracked files had uncommitted changes
- the SHA-256 of `python -m pip freeze`

There is no hand-written text: headings and column labels only. Failing tests stay in the report.

Usage: python -m scripts.render_verification_report
"""

import hashlib
import platform
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path
from typing import Dict, List

BASE_DIR = Path(__file__).resolve().parents[1]
REPORT_PATH = BASE_DIR / "verification" / "REPORT.md"
OUTCOMES = ["passed", "failed", "error", "skipped"]


def _run(cmd: List[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=BASE_DIR, capture_output=True, text=True)


def _cell(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\r", "").replace("\n", "<br>").strip()


def run_verification_suite(xml_path: Path) -> int:
    res = _run([sys.executable, "-m", "pytest", "verification", f"--junitxml={xml_path}", "-q", "-p", "no:cacheprovider"])
    if not xml_path.exists():
        raise RuntimeError(f"pytest did not write junit XML (exit {res.returncode}):\n{res.stdout[-2000:]}\n{res.stderr[-2000:]}")
    return res.returncode


def parse_junit(xml_path: Path) -> Dict:
    root = ET.parse(xml_path).getroot()
    suite = root if root.tag == "testsuite" else root.find("testsuite")
    cases = []
    for tc in suite.iter("testcase"):
        classname = tc.get("classname", "")
        parts = classname.split(".")
        # classname "verification.test_x.TestClass" -> "verification/test_x.py::TestClass"
        module_idx = max(i for i, p in enumerate(parts) if p.startswith("test_")) if any(p.startswith("test_") for p in parts) else len(parts) - 1
        file_part = "/".join(parts[: module_idx + 1]) + ".py"
        class_part = "::".join(parts[module_idx + 1:])
        test_id = "::".join(x for x in (file_part, class_part, tc.get("name", "")) if x)

        outcome, detail = "passed", ""
        for tag in ("failure", "error", "skipped"):
            el = tc.find(tag)
            if el is not None:
                outcome = {"failure": "failed", "error": "error", "skipped": "skipped"}[tag]
                detail = el.get("message", "")
                break
        cases.append({"id": test_id, "outcome": outcome, "detail": detail, "time": float(tc.get("time", 0.0))})

    totals = {k: int(suite.get(k, 0)) for k in ("tests", "failures", "errors", "skipped")}
    totals["time"] = float(suite.get("time", 0.0))
    return {"cases": cases, "totals": totals, "timestamp": suite.get("timestamp", "")}


def build_metadata() -> Dict[str, str]:
    head = _run(["git", "rev-parse", "HEAD"]).stdout.strip()
    dirty = bool(_run(["git", "status", "--porcelain", "--untracked-files=no"]).stdout.strip())
    freeze = _run([sys.executable, "-m", "pip", "freeze"]).stdout
    return {
        "git HEAD": head,
        "tracked files modified": str(dirty).lower(),
        "pip freeze sha256": hashlib.sha256(freeze.encode("utf-8")).hexdigest(),
        "python": platform.python_version(),
    }


def render(parsed: Dict, meta: Dict[str, str], exit_code: int) -> str:
    cases, totals = parsed["cases"], parsed["totals"]
    counts = Counter(c["outcome"] for c in cases)

    # Cross-check parsed test cases against the junit suite totals
    expected = {"failed": totals["failures"], "error": totals["errors"], "skipped": totals["skipped"]}
    if len(cases) != totals["tests"] or any(counts[k] != v for k, v in expected.items()):
        raise RuntimeError(f"junit totals {totals} do not match parsed test cases {dict(counts)}")

    lines = [
        "<!-- Generated by scripts/render_verification_report.py from junit XML. Do not edit by hand. -->",
        "# Verification Report",
        "",
        "## Run",
        "",
        "| Field | Value |",
        "| :--- | :--- |",
    ]
    for key, value in meta.items():
        lines.append(f"| {key} | `{value}` |")
    lines.extend([
        f"| junit timestamp | `{parsed['timestamp']}` |",
        f"| junit time (s) | `{totals['time']:.2f}` |",
        f"| pytest exit code | `{exit_code}` |",
        "",
        "## Summary",
        "",
        "| Outcome | Count |",
        "| :--- | ---: |",
    ])
    for outcome in OUTCOMES:
        lines.append(f"| {outcome} | {counts.get(outcome, 0)} |")
    lines.append(f"| total | {len(cases)} |")
    lines.extend([
        "",
        "## Tests",
        "",
        "| Test | Outcome | Skip reason / failure message |",
        "| :--- | :--- | :--- |",
    ])
    for c in cases:
        lines.append(f"| `{c['id']}` | {c['outcome']} | {_cell(c['detail'])} |")
    return "\n".join(lines) + "\n"


def render_verification_report() -> Path:
    with tempfile.TemporaryDirectory() as tmp:
        xml_path = Path(tmp) / "verification.xml"
        exit_code = run_verification_suite(xml_path)
        parsed = parse_junit(xml_path)
    content = render(parsed, build_metadata(), exit_code)
    REPORT_PATH.write_text(content, encoding="utf-8")
    return REPORT_PATH


if __name__ == "__main__":
    path = render_verification_report()
    print(f"Rendered {path} from junit XML")
